name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 8.x
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        NPM_REGISTRY_URL: https://npm.pkg.github.com
        EMAIL: ${{ secrets.EMAIL }}
    - name: publish
      run: |
        npm config set registry $NPM_REGISTRY_URL 
        npm config set _auth $PERSONAL_ACCESS_TOKEN
        npm config set always-auth=true 
        npm config set email=$EMAIL
        npm run deploy
